# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["you@example.com"]
description = "Fastly Compute static site"
language = "javascript"
manifest_version = 3
name = "interstellar-011-herold_na"
service_id = "D7cNSpyEcY5xeSkHW0Na6b"

[local_server]

  [local_server.kv_stores]

    [local_server.kv_stores.interstellar-011-herold_na-content]
      file = "./static-publisher/kvstore.json"
      format = "json"

[scripts]
  build = "npm run build"

[setup]

  [setup.kv_stores]

    [setup.kv_stores.interstellar-011-herold_na-content]
